myblog/blog/urls.py
from django.conf.urls import url

from blog import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<posting_id>[0-9]+)/comment/$', views.comment, name='comment'),
    url(r'^json/$', views.json_feed, name='json_feed'),
    ]

myblog/myblog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^blog/', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
]

myblog/blog/models.py
import datetime
from django.db import models
from django.utils import timezone


class Posting(models.Model):
    posting_topic = models.CharField(max_length=50, default="New Post")
    posting_text = models.TextField(max_length=2000)
    posting_date = models.DateTimeField('date posted', auto_now_add=True)
    update_date = models.DateTimeField(
        'date updated',
        auto_now=True,
        blank=True,
        null=True)

    def __str__(self):
        return self.posting_topic

    def json(self):
        return {
            'posting_topic': self.posting_topic,
            'posting_text': self.posting_text,
            'posting_date': self.posting_date,
            'update_date': self.update_date,
            'comment': [
                comment.json() for comment in Comment.objects.filter(
                    posting=self).order_by('comment_date')],
            }


class Comment(models.Model):
    posting = models.ForeignKey(Posting, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=500)
    comment_date = models.DateTimeField('date commented')

    def __str__(self):
        return self.comment_text

    def json(self):
        return {
            'comment_text': self.comment_text,
            'comment_date': self.comment_date,
            }

myblog/blog/views.py
import json
from django.core.paginator import Paginator
from django.core.serializers.json import DjangoJSONEncoder
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.utils import timezone
from django.views import generic
from blog.models import Posting, Comment


def json_feed(request):
    data = [posting.json() for posting in Posting.objects.all().order_by(
        '-posting_date')]
    jsonString = json.dumps(data, cls=DjangoJSONEncoder, indent=4)
    with open('blog/rss-json/data.json', 'w') as output:
        json.dump(data, output, cls=DjangoJSONEncoder, indent=4)
    return HttpResponse(jsonString, content_type='application/json')


class IndexView(generic.ListView):
    template_name = 'blog/index.html'
    context_object_name = 'latest_posting_list'
    paginate_by = 5

    def get_queryset(self):
        objects = Posting.objects.all().order_by('-posting_date')
        return objects


class DetailView(generic.DetailView):
    model = Posting
    template_name = 'blog/detail.html'

    def get_queryset(self):
        return Posting.objects.all()


def comment(request, posting_id):
    posting = get_object_or_404(Posting, pk=posting_id)
    p = Posting.objects.get(pk=posting_id)
    user_comment = request.POST['comment_text']
    if not user_comment:
        return render(
            request,
            'blog/detail.html',
            {
                'posting': posting,
                'error_message': "You didn't put a comment!",
            }
         )
    else:
        p.comment_set.create(
            comment_text=user_comment, comment_date=timezone.now())
        p.save()
        return render(
           request,
           'blog/detail.html',
           {
               'posting': posting,
               'success_message': "Your comment has been added!",
            }
        )

myblog/blog/templates/blog/base.html
{% load staticfiles %}
<head>
  <title>MyBlog</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  {% block content %}{% endblock content %}
</body>

myblog/blog/templates/blog/detail.html
{% extends "blog/base.html" %}
{% block content %}
{% load staticfiles %}
<h1>{{ posting.posting_topic }}</h1>
<blockquote>
  <p class="posting_text">{{ posting.posting_text }}</p>
  <footer class="posting_date">Posted on {{ posting.posting_date }}</footer>
</blockquote>

<div id = "commenting">
  <ul>{% if error_message %}<p class="error_message"><strong>{{ error_message }}</strong></p>{% endif %}</ul>
  <ul>{% if success_message %}<p class="success_message"><strong>{{ success_message }}</strong></p>{% endif %}</ul>
  <ul>
  {% for comment in posting.comment_set.all %}
    <li><p class="comment_text">{{ comment.comment_text }} - {{ comment.comment_date }}</p></li>
  {% endfor %}
  <form action="{% url 'blog:comment' posting.id %}" method="post">
    {% csrf_token %}
    <textarea name="comment_text" cols="80" rows="3"></textarea><br/>
    <button type="submit" class="btn btn-primary btn-sm">Submit</button>
    <button type="reset" class="btn btn-primary btn-sm">Erase</button>
  </form>
  </ul>
</div>

<ul>
  <button type="button" class="btn btn-success btn-sm" id="back">Go to Main Page</button>
  <button type="button" class="btn btn-success btn-sm" id="show">Show Comments</button>
  <button type="button" class="btn btn-success btn-sm" id="hide">Hide Comments</button>
</ul>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="{% static 'js/blog.js' %}"></script>
{% endblock content %}

myblog/blog/templates/blog/index.html
{% extends "blog/base.html" %}
{% block content %}
{% load staticfiles %}
<h1>My Blog</h1>
<blockquote>
  <strong><p class="posting_text">Latest postings:</p></strong>
  <a href="{% url 'blog:json_feed' %}"> <img title="RSS-JSON" src="{% static "images/rss.png" %}" alt="RSS" width="25" height="25" align="left"> </a>
</blockquote>

{% if latest_posting_list %}
    <ul>
    {% for posting in latest_posting_list %}
        <li><a href="{% url 'blog:detail' posting.id %}">{{ posting.posting_topic }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No postings are available.</p>
{% endif %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a class="btn btn-primary  btn-sm" role="button"  href="?page={{ page_obj.previous_page_number }}">Previous page</a>
        {% endif %}
        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>
        {% if page_obj.has_next %}
            <a class="btn btn-primary  btn-sm" role="button"  href="?page={{ page_obj.next_page_number }}">Next page</a>
        {% endif %}
    </span>
</div>
{% endblock content %}